version: '3.3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'mysql_dev'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'mysql_dev'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
      command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3306'
    volumes:
      - ./:/docker-entrypoint-initdb.d
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
